# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages
warnings_are_errors: true

## Necessary for gifski dependency
addons:
  apt:
    packages:
      - cargo
      - libmagick++-dev

before_install:
  - gcc --version
  - g++ --version
  - Rscript -e "source('build_steps.R'); before_install()"

after_success:
   - Rscript -e "source('build_steps.R'); after_success(); unlink('build_steps.R')"
   - Rscript -e 'if(Sys.info()["sysname"] != "Linux"){q()}; library(covr); flags <- getOption("covr.flags"); flags[] <- gsub("-O0 ", "", flags); options(covr.flags=flags); codecov(quiet=FALSE)'

branches:
  except:
    - master # Don't build "master" branch or we get in an infinite loop

r_build_args: --no-manual --no-resave-data
r_check_args: --no-manual

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: develop
  local_dir: .
  target_branch: master
  condition: $TRAVIS_OS_NAME = "linux"
