`%||%` <- function(x, y){
  if( (!is.null(x)) && (nzchar(x)) ){
    x
  } else {
    y
  }
}

before_install <- function(){
  ## Build various bits of autogenerated code
  cat("INSTALLING BUILD DEPENDENCIES -------- \n\n")
  for(pkg in c("devtools", "roxygen2", "testthat", "rmarkdown", "pkgdown")){
    if(!require(pkg, character.only=TRUE)){
      install.packages(pkg)
    }
  }
  cat("INSTALLING RUN DEPENDENCIES -------- \n\n")
  devtools::install_deps(dependencies=c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances"),
                         quiet=FALSE, upgrade=FALSE, auth_token = Sys.getenv("GITHUB_PAT") %||% devtools::github_pat(FALSE))

  cat("BUILDING NAMESPACE with roxygen2 -------- \n\n")
  roxygen2::roxygenize()
  cat("COMPILING RCPP ATTRIBUTES -------- \n\n")
  Rcpp::compileAttributes(verbose=TRUE)
  cat("WRITING DOCUMENTATION -------- \n\n")
  # Shell out to devtools::document to avoid weird reload error
  system("Rscript -e 'devtools::document()'")

  ## Write test stubs to avoid TravisCI time outs when running "coverage version"
  cat("WRITING TEST STUBS -------- \n\n")
  skeleton <- readLines(file.path("tests", "test_stub.R"))
  for(f in list.files(file.path("tests", "testthat"), pattern="test_")){
    stub <- gsub("test_(.*)\\.R", "\\1", f)
    writeLines(gsub("PATTERN", stub, skeleton),
               file.path("tests", paste0("test_", stub, ".R")))
  }
  unlink(file.path("tests", "test_stub.R"))

  ## GitHash for debugging purposes
  cat("ADDING GIT HASH -------- \n\n")
  if(!dir.exists("inst")){
    dir.create("inst")
  }
  writeLines(system("git rev-parse HEAD", intern=TRUE), "inst/GIT.HASH")
}

after_success <- function(){
  devtools::install(reload = TRUE, quick = TRUE, quiet = FALSE, upgrade = FALSE, 
                    auth_token = Sys.getenv("GITHUB_TOKEN") %||% devtools::github_pat(FALSE))
  rmarkdown::render("README.Rmd", clean = FALSE)
  unlink("README.knit.md", force = TRUE)
  unlink("README.utf8.md", force = TRUE)

  ## Build pkgdown site
  pkgdown::build_site()

  ## Copy GIF to a place where pkgdown site will find it
  dir.create("docs/inst", recursive = TRUE)
  file.copy("inst/path_dyn.gif", "docs/inst/path_dyn.gif")

  ## Clean up build artifacts
  unlink(Sys.glob("clustRviz.Rcheck"), recursive=TRUE, force=TRUE)
  unlink(Sys.glob("clustRviz*.tar.gz"), recursive=TRUE, force=TRUE)
  file.rename(".gitignore.deploy", ".gitignore")
  unlink(Sys.glob("src/*o"), force=TRUE)
}
