before_install <- function(){
  ## Build various bits of autogenerated code
  cat("INSTALLING BUILD DEPENDENCIES -------- \n\n")
  for(pkg in c("devtools", "roxygen2", "testthat", "rmarkdown", "pkgdown")){
    if(!require(pkg, character.only=TRUE)){
      install.packages(pkg)
    }
  }
  cat("INSTALLING RUN DEPENDENCIES -------- \n\n")
  devtools::install_deps(dependencies=c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances"),
                         quiet=FALSE, upgrade=TRUE)

  cat("BUILDING NAMESPACE with roxygen2 -------- \n\n")
  roxygen2::roxygenize()
  cat("COMPILING RCPP ATTRIBUTES -------- \n\n")
  Rcpp::compileAttributes(verbose=TRUE)
  cat("WRITING DOCUMENTATION -------- \n\n")
  # Shell out to devtools::document to avoid weird reload error
  system("Rscript -e 'devtools::document()'")

  ## GitHash for debugging purposes
  cat("ADDING GIT HASH -------- \n\n")
  if(!dir.exists("inst")){
    dir.create("inst")
  }
  writeLines(system("git rev-parse HEAD", intern=TRUE), "inst/GIT.HASH")
}

after_success <- function(){
  devtools::install()
  rmarkdown::render("README.Rmd")
  pkgdown::build_site()
  unlink(Sys.glob("clustRviz.Rcheck"), recursive=TRUE, force=TRUE)
  unlink(Sys.glob("clustRviz*.tar.gz"), recursive=TRUE, force=TRUE)
  file.rename(".gitignore.deploy", ".gitignore")
  unlink(Sys.glob("src/*o"), force=TRUE)
}
