# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CARPcpp <- function(X, M, D, weights, epsilon, t, rho = 1, thresh, max_iter = 100000L, max_inner_iter = 2500L, burn_in = 50L, back = 0.5, keep = 10L, viz_max_inner_iter = 15L, viz_initial_step = 1.1, viz_small_step = 1.01, l1 = FALSE, show_progress = TRUE, back_track = FALSE, exact = FALSE) {
    .Call('_clustRviz_CARPcpp', PACKAGE = 'clustRviz', X, M, D, weights, epsilon, t, rho, thresh, max_iter, max_inner_iter, burn_in, back, keep, viz_max_inner_iter, viz_initial_step, viz_small_step, l1, show_progress, back_track, exact)
}

CBASScpp <- function(X, M, D_row, D_col, weights_row, weights_col, epsilon, t, thresh, rho = 1, max_iter = 100000L, max_inner_iter = 2500L, burn_in = 50L, back = 0.5, keep = 10L, viz_max_inner_iter = 15L, viz_initial_step = 1.1, viz_small_step = 1.01, l1 = FALSE, show_progress = TRUE, back_track = FALSE, exact = FALSE) {
    .Call('_clustRviz_CBASScpp', PACKAGE = 'clustRviz', X, M, D_row, D_col, weights_row, weights_col, epsilon, t, thresh, rho, max_iter, max_inner_iter, burn_in, back, keep, viz_max_inner_iter, viz_initial_step, viz_small_step, l1, show_progress, back_track, exact)
}

ConvexClusteringCPP <- function(X, M, D, weights, lambda_grid, rho = 1, thresh, max_iter = 100000L, max_inner_iter = 2500L, l1 = FALSE, show_progress = TRUE) {
    .Call('_clustRviz_ConvexClusteringCPP', PACKAGE = 'clustRviz', X, M, D, weights, lambda_grid, rho, thresh, max_iter, max_inner_iter, l1, show_progress)
}

ConvexBiClusteringCPP <- function(X, M, D_row, D_col, weights_row, weights_col, lambda_grid, rho = 1, thresh, max_iter = 100000L, max_inner_iter = 2500L, l1 = FALSE, show_progress = TRUE) {
    .Call('_clustRviz_ConvexBiClusteringCPP', PACKAGE = 'clustRviz', X, M, D_row, D_col, weights_row, weights_col, lambda_grid, rho, thresh, max_iter, max_inner_iter, l1, show_progress)
}

clustRviz_set_logger_level_cpp <- function(level) {
    invisible(.Call('_clustRviz_clustRviz_set_logger_level_cpp', PACKAGE = 'clustRviz', level))
}

clustRviz_get_logger_level_cpp <- function() {
    .Call('_clustRviz_clustRviz_get_logger_level_cpp', PACKAGE = 'clustRviz')
}

clustRviz_log_cpp <- function(level, x) {
    invisible(.Call('_clustRviz_clustRviz_log_cpp', PACKAGE = 'clustRviz', level, x))
}

get_cluster_assignments <- function(E, edge_ind, n) {
    .Call('_clustRviz_get_cluster_assignments', PACKAGE = 'clustRviz', E, edge_ind, n)
}

MatrixRowProx <- function(X, lambda, weights, l1 = TRUE) {
    .Call('_clustRviz_MatrixRowProx', PACKAGE = 'clustRviz', X, lambda, weights, l1)
}

MatrixColProx <- function(X, lambda, weights, l1 = TRUE) {
    .Call('_clustRviz_MatrixColProx', PACKAGE = 'clustRviz', X, lambda, weights, l1)
}

check_weight_matrix <- function(weight_matrix) {
    invisible(.Call('_clustRviz_check_weight_matrix', PACKAGE = 'clustRviz', weight_matrix))
}

smooth_u_clustering <- function(U_old, cluster_info_list) {
    .Call('_clustRviz_smooth_u_clustering', PACKAGE = 'clustRviz', U_old, cluster_info_list)
}

tensor_projection <- function(X, Y) {
    .Call('_clustRviz_tensor_projection', PACKAGE = 'clustRviz', X, Y)
}

