# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib clustRviz
NULL

ProxL1 <- function(delta, p, lambda, weights) {
    .Call('_clustRviz_ProxL1', PACKAGE = 'clustRviz', delta, p, lambda, weights)
}

CARPL2_VIS_FRAC <- function(x, n, p, lambda_init, weights, uinit, vinit, premat, IndMat, EOneIndMat, ETwoIndMat, rho = 1, max_iter = 1e4L, burn_in = 50L, verbose = FALSE, back = 0.5, try_tol = 1e-3, ti = 15L, t_switch = 1.01, keep = 10L) {
    .Call('_clustRviz_CARPL2_VIS_FRAC', PACKAGE = 'clustRviz', x, n, p, lambda_init, weights, uinit, vinit, premat, IndMat, EOneIndMat, ETwoIndMat, rho, max_iter, burn_in, verbose, back, try_tol, ti, t_switch, keep)
}

CARPL2_NF_FRAC <- function(x, n, p, lambda_init, t, weights, uinit, vinit, premat, IndMat, EOneIndMat, ETwoIndMat, rho = 1, max_iter = 1e4L, burn_in = 50L, verbose = FALSE, keep = 10L) {
    .Call('_clustRviz_CARPL2_NF_FRAC', PACKAGE = 'clustRviz', x, n, p, lambda_init, t, weights, uinit, vinit, premat, IndMat, EOneIndMat, ETwoIndMat, rho, max_iter, burn_in, verbose, keep)
}

CARPL1_NF_FRAC <- function(x, n, p, lambda_init, t, weights, uinit, vinit, premat, IndMat, EOneIndMat, ETwoIndMat, rho = 1, max_iter = 1e4L, burn_in = 50L, verbose = FALSE, keep = 10L) {
    .Call('_clustRviz_CARPL1_NF_FRAC', PACKAGE = 'clustRviz', x, n, p, lambda_init, t, weights, uinit, vinit, premat, IndMat, EOneIndMat, ETwoIndMat, rho, max_iter, burn_in, verbose, keep)
}

CARPL1_VIS_FRAC <- function(x, n, p, lambda_init, weights, uinit, vinit, premat, IndMat, EOneIndMat, ETwoIndMat, rho = 1, max_iter = 1e4L, burn_in = 50L, verbose = FALSE, back = 0.5, try_tol = 1e-3, ti = 15L, t_switch = 1.01, keep = 10L) {
    .Call('_clustRviz_CARPL1_VIS_FRAC', PACKAGE = 'clustRviz', x, n, p, lambda_init, weights, uinit, vinit, premat, IndMat, EOneIndMat, ETwoIndMat, rho, max_iter, burn_in, verbose, back, try_tol, ti, t_switch, keep)
}

BICARPL2_VIS <- function(x, n, p, lambda_init, weights_col, weights_row, uinit_row, uinit_col, vinit_row, vinit_col, premat_row, premat_col, IndMat_row, IndMat_col, EOneIndMat_row, EOneIndMat_col, ETwoIndMat_row, ETwoIndMat_col, rho = 1, max_iter = 1e4L, burn_in = 50L, verbose = FALSE, verbose_inner = FALSE, try_tol = 1e-3, ti = 15L, t_switch = 1.01) {
    .Call('_clustRviz_BICARPL2_VIS', PACKAGE = 'clustRviz', x, n, p, lambda_init, weights_col, weights_row, uinit_row, uinit_col, vinit_row, vinit_col, premat_row, premat_col, IndMat_row, IndMat_col, EOneIndMat_row, EOneIndMat_col, ETwoIndMat_row, ETwoIndMat_col, rho, max_iter, burn_in, verbose, verbose_inner, try_tol, ti, t_switch)
}

BICARPL1_VIS <- function(x, n, p, lambda_init, weights_col, weights_row, uinit_row, uinit_col, vinit_row, vinit_col, premat_row, premat_col, IndMat_row, IndMat_col, EOneIndMat_row, EOneIndMat_col, ETwoIndMat_row, ETwoIndMat_col, rho = 1, max_iter = 1e4L, burn_in = 50L, verbose = FALSE, verbose_inner = FALSE, try_tol = 1e-3, ti = 15L, t_switch = 1.01) {
    .Call('_clustRviz_BICARPL1_VIS', PACKAGE = 'clustRviz', x, n, p, lambda_init, weights_col, weights_row, uinit_row, uinit_col, vinit_row, vinit_col, premat_row, premat_col, IndMat_row, IndMat_col, EOneIndMat_row, EOneIndMat_col, ETwoIndMat_row, ETwoIndMat_col, rho, max_iter, burn_in, verbose, verbose_inner, try_tol, ti, t_switch)
}

BICARPL2_NF_FRAC <- function(x, n, p, lambda_init, t, weights_row, weights_col, uinit_row, uinit_col, vinit_row, vinit_col, premat_row, premat_col, IndMat_row, IndMat_col, EOneIndMat_row, EOneIndMat_col, ETwoIndMat_row, ETwoIndMat_col, rho = 1, max_iter = 1e4L, burn_in = 50L, verbose = FALSE, keep = 10L) {
    .Call('_clustRviz_BICARPL2_NF_FRAC', PACKAGE = 'clustRviz', x, n, p, lambda_init, t, weights_row, weights_col, uinit_row, uinit_col, vinit_row, vinit_col, premat_row, premat_col, IndMat_row, IndMat_col, EOneIndMat_row, EOneIndMat_col, ETwoIndMat_row, ETwoIndMat_col, rho, max_iter, burn_in, verbose, keep)
}

BICARPL1_NF_FRAC <- function(x, n, p, lambda_init, t, weights_row, weights_col, uinit_row, uinit_col, vinit_row, vinit_col, premat_row, premat_col, IndMat_row, IndMat_col, EOneIndMat_row, EOneIndMat_col, ETwoIndMat_row, ETwoIndMat_col, rho = 1, max_iter = 1e4L, burn_in = 50L, verbose = FALSE, keep = 10L) {
    .Call('_clustRviz_BICARPL1_NF_FRAC', PACKAGE = 'clustRviz', x, n, p, lambda_init, t, weights_row, weights_col, uinit_row, uinit_col, vinit_row, vinit_col, premat_row, premat_col, IndMat_row, IndMat_col, EOneIndMat_row, EOneIndMat_col, ETwoIndMat_row, ETwoIndMat_col, rho, max_iter, burn_in, verbose, keep)
}

